name: CI

on: [push, pull_request]

jobs:
  run:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@master
        with:
          fetch-depth: 3
      
      - name: Clone repository
        run: curl https://dlang.org/install.sh | bash -s

      - name: Run tests
        run: ~/dlang/install.sh dmd -de -main -o- -unittest src/matrix.d
