name: Test

on: [push]

jobs:
  run:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - uses: WebFreak001/setup-dmd@v1
        with:
          dmd-version: 2.088.0

      - name: Run tests
        run: dmd -de -main -o- -unittest src/matrix.d
