name: Test

on: [push]

jobs:
  run:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest

      - name: Run tests
        run: dmd -de -main -o- -unittest src/matrix.d
