name: CI

on: [push, pull_request]

jobs:
  run:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@master
        with:
          fetch-depth: 3

      - name: Run tests
        run: dmd -de -main -o- -unittest src/matrix.d
