name: CI

on: [push]

jobs:
  run:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@master
        with:
          fetch-depth: 3
      
      - name: Install dmd
        run: curl https://dlang.org/install.sh | bash -s

      - name: Activate dmd
        run: source ~/dlang/dmd-2.088.0/activate

      - name: Run tests
        run: /bin/bash -e "dmd -de -main -o- -unittest src/matrix.d"
